"""Quarterly validation per agent spec §Validation protocol.

1. HSW elasticity on Bolivia: regress departmental log(GDP) on log(SOL)
   annually and confirm ∂log(GDP)/∂log(SOL) ∈ [0.20, 0.35].
2. VNF–YPFB monthly correlation ≥ 0.80.
3. S5P–fuel-sales monthly correlation ≥ 0.60 on detrended series (La Paz + SCZ).

Emits a JSON with pass/fail per check. If any fail, the monthly publication
should be halted by the harness runner reading this artifact.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _common import abs_path, load_env, paths  # noqa: E402

load_env()


def hsw_elasticity() -> dict:
    """Departmental GDP × SOL. Expects optional data/official/ine_gdp_dept.csv
    with columns (year, department, gdp_usd) and a departmental SOL file
    generated by the departmental aggregation path (not bundled by default)."""
    dept_gdp = abs_path("data/official/ine_gdp_dept.csv")
    dept_sol = abs_path("data/satellite/viirs_sol_dept_annual.csv")
    if not dept_gdp.exists() or not dept_sol.exists():
        return {"status": "inputs_missing"}
    a = pd.read_csv(dept_gdp)
    b = pd.read_csv(dept_sol)
    df = a.merge(b, on=["year", "department"])
    df = df[(df["gdp_usd"] > 0) & (df["sol"] > 0)]
    if len(df) < 20:
        return {"status": "n_too_small", "n": len(df)}
    x = np.log(df["sol"])
    y = np.log(df["gdp_usd"])
    beta, _ = np.polyfit(x, y, 1)
    return {"status": "ok", "beta": float(beta),
            "pass": 0.20 <= beta <= 0.35, "n": int(len(df))}


def vnf_ypfb_corr() -> dict:
    p = paths()
    vnf = pd.read_csv(abs_path(p["data"]["vnf_anomaly"]))
    ypfb_path = abs_path(p["data"]["official_ypfb"])
    if not ypfb_path.exists() or vnf.empty:
        return {"status": "inputs_missing"}
    y = pd.read_csv(ypfb_path, parse_dates=["date"])
    vnf["date"] = pd.to_datetime(vnf["date"])
    m = vnf.merge(y, on="date").dropna(subset=["log_rh", "gas_prod_mmm3d"])
    if len(m) < 24:
        return {"status": "n_too_small", "n": len(m)}
    c = float(np.corrcoef(m["log_rh"], np.log(m["gas_prod_mmm3d"]))[0, 1])
    return {"status": "ok", "corr": c, "pass": c >= 0.80, "n": int(len(m))}


def s5p_fuel_corr() -> dict:
    p = paths()
    db_path = abs_path(p["data"]["ci_db"])
    fuel_path = abs_path("data/official/ypfb_fuel_sales_metro.csv")
    if not fuel_path.exists() or not db_path.exists():
        return {"status": "inputs_missing"}
    con = duckdb.connect(str(db_path), read_only=True)
    try:
        ci = con.execute("SELECT * FROM ci").df()
    finally:
        con.close()
    fuel = pd.read_csv(fuel_path, parse_dates=["date"])
    m = ci.merge(fuel, on="date").dropna(subset=["no2_z", "fuel_sales_metro"])
    if len(m) < 24:
        return {"status": "n_too_small", "n": len(m)}
    # Detrend by first-differencing
    x = m["no2_z"].diff().dropna()
    y = np.log(m["fuel_sales_metro"]).diff().dropna()
    k = min(len(x), len(y))
    c = float(np.corrcoef(x.tail(k), y.tail(k))[0, 1])
    return {"status": "ok", "corr": c, "pass": c >= 0.60, "n": int(k)}


def main() -> None:
    result = {
        "hsw_elasticity": hsw_elasticity(),
        "vnf_ypfb_corr": vnf_ypfb_corr(),
        "s5p_fuel_corr": s5p_fuel_corr(),
    }
    any_fail = any(
        r.get("status") == "ok" and r.get("pass") is False for r in result.values()
    )
    result["halt_publication"] = any_fail
    out = abs_path("data/satellite/validation.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2))
    print(f"[ok] validation → {out}  halt={any_fail}")


if __name__ == "__main__":
    main()
